services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - observability-network

  goapp-service-a:
    container_name: goapp-a-cep-input
    build:
      context: ./service-a-cep-input
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - zipkin
      - goapp-service-b
    networks:
      - observability-network

  goapp-service-b:
    container_name: goapp-b-weather-api
    build:
      context: ./service-b-weather-api
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - zipkin
    networks:
      - observability-network

networks:
  observability-network:
    driver: bridge
