### 200 valid CEP
# curl --location 'http://localhost:8080'
#--header 'Content-Type: application/json'
#--data '{
#  "cep": "29902555"
#}'
POST http://localhost:8080
Content-Type: application/json

{
  "cep": "29902555"
}

###

### 422 invalid CEP
# curl --location 'http://localhost:8080'
#--header 'Content-Type: application/json'
#--data '{
#  "cep": "99999999"
#}'
POST http://localhost:8080
Content-Type: application/json

{
  "cep": "99999999"
}

###
